### ISSUE TITLE
TypeError: Cannot read property 'left' of undefined

### ISSUE THREAD

**Issue by alexcroox** [Splidejs/vue-splide#1]
I'm getting the following error on page load. I'm using a main gallery with a synced thumbnail gallery:

`TypeError: Cannot read property 'left' of undefined`

Setting a breakpoint it seems `this.padding` becomes `undefined` during mount, it doesn't matter if I provide options.padding or not.

```
get width() {
      return track.clientWidth - this.padding.left - this.padding.right;
},
```

I don't have an easy reproducible example as I have quite a complex gallery and I'm ripping out one library for another. Hoping it's something obvious to you in the logic of: https://github.com/Splidejs/splide/blob/fe53e80423e04615231b59c64b069ddd296dd44b/src/js/components/layout/directions/horizontal.js#L74-L78

**Comment by Splidejs** [comment]
The problem has been fixed in the latest version(splide v2.4.3, vue-splide v0.3.0).

**Comment by alexcroox** [comment]
Confirmed fixed, thank you!!

**Comment by alexcroox** [comment]
Unfortunately I am still getting this since updating the css to the latest (unsure if related or coincidence)

**Comment by NaotoshiFujita** [comment]
I could not reproduce this bug. My examples made by Vue-Splide work correctly, using the latest version script and CSS.
https://splidejs.github.io/vue-splide/

Please give me jsfiddle or codepen.

**Comment by alexcroox** [comment]
Update on this one, I'm still unable to get past the fatal error where this.padding is undefined when `get width()` is being called inside the horizontal slider. Currently manually editing the source to this has fixed my issue locally while I try work out the root of the problem in the splide source:

```
get width() {
      if (!this.padding) {
        this.padding = {
          left: 0,
          right: 0
        }
      }
       return track.clientWidth - this.padding.left - this.padding.right;
    }
```

**Comment by alexcroox** [comment]
More digging, it appears the error originates from the following call:

```
bind() {
    EVENTS.forEach( event => {
        this.splide.on( event, ( ...args ) => {
            this.$emit( `splide:${ event }`, this.splide, ...args );
        } );
    } );
},
```

**Comment by NaotoshiFujita** [comment]
Can you tell the suspicious difference between [my thumbnail slider example](https://github.com/Splidejs/vue-splide/blob/master/examples/src/js/examples/components/ThumbnailsExample.vue) and yours?

I still don't have any clue because I cannot reproduce the bug in my environment.
If you paste your code, it might be also helpful.

**Comment by alexcroox** [comment]
Sure, sorry I know it's super hard to debug when you can't produce and when I can't provide a small reproducible example, here is my code in case there's anything that jumps out:

https://pastebin.com/GQZkdMew

I've removed a lot of irrelevant stuff to try to make it easier to visually parse

**Comment by NaotoshiFujita** [comment]
I haven't been able to reproduce the bug, but while scrutinizing this issue, I found the padding became `undefined` when I converted the Splide instance to a JSON string with `JSON.stringify()`. I don't think this is not related with this bug.

Can you try again with Vue-Splide v0.3.2? Please disable your modification before verifying it.

**Comment by alexcroox** [comment]
Yes fantastic thank you, I `rm -rf node_modules` before hand to make sure and I've not seen the error since. Thank you!!
